Update scanner.yaml

diff --git a/.github/workflows/scanner.yaml b/.github/workflows/scanner.yaml
--- a/.github/workflows/scanner.yaml
+++ b/.github/workflows/scanner.yaml
@@ -62,24 +62,13 @@ jobs:
           CLIENT_REPO_PR_TITLE: ${{ github.event.pull_request.title }}
         run: |
           cd scripts/scripts
-          pwd
-          ls
-          # pipenv install
-          # pipenv install --dev
-          echo "Dependency Install Successfully Completed"
-          # pipenv run python3 -m scanner
-          # snyk --version
-          cd ..
-          pwd
-          ls
-          cd ..
-          ls
-          pwd
+          pipenv install
+          pipenv install --dev
+          pipenv run python3 -m scanner
+          snyk --version
+          cd ../..
           cd client_repo
-          ls
-          pwd
-          
-          # snyk test
+          snyk test
           
       
       - name: Run GitGuardian Code Scanning Script
@@ -92,17 +81,17 @@ jobs:
           echo "Image Build Process and Wiz Scan Results are here"
 
 
-      # - name: Add the Full PullRequest Code Scan Summary as A comment in the PR
-      #   uses: actions/github-script@v7
-      #   with:
-      #     github-token: ${{ secrets.PR_GITHUB_TOKEN }}
-      #     script: |
-      #       github.rest.issues.createComment({
-      #         issue_number: context.issue.number,
-      #         owner: context.repo.owner,
-      #         repo: context.repo.repo,
-      #         body: '${{ steps.scan.outputs.scanSummary }}'
-      #       })
+      - name: Add the Full PullRequest Code Scan Summary as A comment in the PR
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{ secrets.PR_GITHUB_TOKEN }}
+          script: |
+            github.rest.issues.createComment({
+              issue_number: context.issue.number,
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              body: '${{ steps.scan.outputs.scanSummary }}'
+            })
 
             
       - name: Send Data to the Monitoring Dashboard
@@ -110,15 +99,15 @@ jobs:
           echo "Scan Summary Data Processed to the Dashboard"
 
       
-      # - name: Enforce Custom Policy as Code to the Repository
-      #   env:
-      #     policy_output: ${{ steps.scan.outputs.scanSummary }}
-      #   run: |
-      #     policy_result=$(echo "$policy_output" | jq -r '.policy_result')
-      #     echo "Policy Result: $policy_result"
-      #     if [ "$policy_result" == "fail" ]; then
-      #       echo "Policy Check Failed"
-      #       exit 1
-      #     else
-      #       echo "Policy Check Passed"
-      #     fi
+      - name: Enforce Custom Policy as Code to the Repository
+        env:
+          policy_output: ${{ steps.scan.outputs.scanSummary }}
+        run: |
+          policy_result=$(echo "$policy_output" | jq -r '.policy_result')
+          echo "Policy Result: $policy_result"
+          if [ "$policy_result" == "fail" ]; then
+            echo "Policy Check Failed"
+            exit 1
+          else
+            echo "Policy Check Passed"
+          fi
