Update scanner.yaml

diff --git a/.github/workflows/scanner.yaml b/.github/workflows/scanner.yaml
--- a/.github/workflows/scanner.yaml
+++ b/.github/workflows/scanner.yaml
@@ -100,15 +100,15 @@ jobs:
           echo "Scan Summary Data Processed to the Dashboard"
 
       
-      - name: Enforce Custom Policy as Code to the Repository
-        env:
-          policy_output: ${{ steps.scan.outputs.scanSummary }}
-        run: |
-          policy_result=$(echo "$policy_output" | jq -r '.policy_result')
-          echo "Policy Result: $policy_result"
-          if [ "$policy_result" == "fail" ]; then
-            echo "Policy Check Failed"
-            exit 1
-          else
-            echo "Policy Check Passed"
-          fi
+      # - name: Enforce Custom Policy as Code to the Repository
+      #   env:
+      #     policy_output: ${{ steps.scan.outputs.scanSummary }}
+      #   run: |
+      #     policy_result=$(echo "$policy_output" | jq -r '.policy_result')
+      #     echo "Policy Result: $policy_result"
+      #     if [ "$policy_result" == "fail" ]; then
+      #       echo "Policy Check Failed"
+      #       exit 1
+      #     else
+      #       echo "Policy Check Passed"
+      #     fi
